/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventoEventoIdRouteImport } from './routes/evento/$eventoId'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppUsuariosIndexRouteImport } from './routes/app/usuarios/index'
import { Route as AppUsuariosCriarRouteImport } from './routes/app/usuarios/criar'
import { Route as AppPerfilUserIdRouteImport } from './routes/app/perfil/$userId'
import { Route as AppEventoCriarRouteImport } from './routes/app/evento/criar'
import { Route as AppPerfilEditarSelfRouteImport } from './routes/app/perfil/editar.self'
import { Route as AppEventoEditarEventoIdRouteImport } from './routes/app/evento/editar.$eventoId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoEventoIdRoute = EventoEventoIdRouteImport.update({
  id: '/evento/$eventoId',
  path: '/evento/$eventoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsuariosIndexRoute = AppUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsuariosCriarRoute = AppUsuariosCriarRouteImport.update({
  id: '/usuarios/criar',
  path: '/usuarios/criar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerfilUserIdRoute = AppPerfilUserIdRouteImport.update({
  id: '/perfil/$userId',
  path: '/perfil/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventoCriarRoute = AppEventoCriarRouteImport.update({
  id: '/evento/criar',
  path: '/evento/criar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerfilEditarSelfRoute = AppPerfilEditarSelfRouteImport.update({
  id: '/perfil/editar/self',
  path: '/perfil/editar/self',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventoEditarEventoIdRoute = AppEventoEditarEventoIdRouteImport.update({
  id: '/evento/editar/$eventoId',
  path: '/evento/editar/$eventoId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/evento/$eventoId': typeof EventoEventoIdRoute
  '/app/evento/criar': typeof AppEventoCriarRoute
  '/app/perfil/$userId': typeof AppPerfilUserIdRoute
  '/app/usuarios/criar': typeof AppUsuariosCriarRoute
  '/app/usuarios': typeof AppUsuariosIndexRoute
  '/app/evento/editar/$eventoId': typeof AppEventoEditarEventoIdRoute
  '/app/perfil/editar/self': typeof AppPerfilEditarSelfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/evento/$eventoId': typeof EventoEventoIdRoute
  '/app/evento/criar': typeof AppEventoCriarRoute
  '/app/perfil/$userId': typeof AppPerfilUserIdRoute
  '/app/usuarios/criar': typeof AppUsuariosCriarRoute
  '/app/usuarios': typeof AppUsuariosIndexRoute
  '/app/evento/editar/$eventoId': typeof AppEventoEditarEventoIdRoute
  '/app/perfil/editar/self': typeof AppPerfilEditarSelfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/evento/$eventoId': typeof EventoEventoIdRoute
  '/app/evento/criar': typeof AppEventoCriarRoute
  '/app/perfil/$userId': typeof AppPerfilUserIdRoute
  '/app/usuarios/criar': typeof AppUsuariosCriarRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
  '/app/evento/editar/$eventoId': typeof AppEventoEditarEventoIdRoute
  '/app/perfil/editar/self': typeof AppPerfilEditarSelfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/auth/sign-in'
    | '/evento/$eventoId'
    | '/app/evento/criar'
    | '/app/perfil/$userId'
    | '/app/usuarios/criar'
    | '/app/usuarios'
    | '/app/evento/editar/$eventoId'
    | '/app/perfil/editar/self'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/auth/sign-in'
    | '/evento/$eventoId'
    | '/app/evento/criar'
    | '/app/perfil/$userId'
    | '/app/usuarios/criar'
    | '/app/usuarios'
    | '/app/evento/editar/$eventoId'
    | '/app/perfil/editar/self'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/auth/sign-in'
    | '/evento/$eventoId'
    | '/app/evento/criar'
    | '/app/perfil/$userId'
    | '/app/usuarios/criar'
    | '/app/usuarios/'
    | '/app/evento/editar/$eventoId'
    | '/app/perfil/editar/self'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  EventoEventoIdRoute: typeof EventoEventoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/$eventoId': {
      id: '/evento/$eventoId'
      path: '/evento/$eventoId'
      fullPath: '/evento/$eventoId'
      preLoaderRoute: typeof EventoEventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usuarios/': {
      id: '/app/usuarios/'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usuarios/criar': {
      id: '/app/usuarios/criar'
      path: '/usuarios/criar'
      fullPath: '/app/usuarios/criar'
      preLoaderRoute: typeof AppUsuariosCriarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/perfil/$userId': {
      id: '/app/perfil/$userId'
      path: '/perfil/$userId'
      fullPath: '/app/perfil/$userId'
      preLoaderRoute: typeof AppPerfilUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/evento/criar': {
      id: '/app/evento/criar'
      path: '/evento/criar'
      fullPath: '/app/evento/criar'
      preLoaderRoute: typeof AppEventoCriarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/perfil/editar/self': {
      id: '/app/perfil/editar/self'
      path: '/perfil/editar/self'
      fullPath: '/app/perfil/editar/self'
      preLoaderRoute: typeof AppPerfilEditarSelfRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/evento/editar/$eventoId': {
      id: '/app/evento/editar/$eventoId'
      path: '/evento/editar/$eventoId'
      fullPath: '/app/evento/editar/$eventoId'
      preLoaderRoute: typeof AppEventoEditarEventoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventoCriarRoute: typeof AppEventoCriarRoute
  AppPerfilUserIdRoute: typeof AppPerfilUserIdRoute
  AppUsuariosCriarRoute: typeof AppUsuariosCriarRoute
  AppUsuariosIndexRoute: typeof AppUsuariosIndexRoute
  AppEventoEditarEventoIdRoute: typeof AppEventoEditarEventoIdRoute
  AppPerfilEditarSelfRoute: typeof AppPerfilEditarSelfRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEventoCriarRoute: AppEventoCriarRoute,
  AppPerfilUserIdRoute: AppPerfilUserIdRoute,
  AppUsuariosCriarRoute: AppUsuariosCriarRoute,
  AppUsuariosIndexRoute: AppUsuariosIndexRoute,
  AppEventoEditarEventoIdRoute: AppEventoEditarEventoIdRoute,
  AppPerfilEditarSelfRoute: AppPerfilEditarSelfRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  EventoEventoIdRoute: EventoEventoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
